In [19]:
import numpy as np 
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.metrics import accuracy_score

In [8]:
iris = load_iris()
x, y = iris.data, iris.target

In [9]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.20,random_state=0)

In [10]:
from sklearn.ensemble import AdaBoostClassifier

abc = AdaBoostClassifier(n_estimators=50,learning_rate=1)
model = abc.fit(x_train,y_train)
y_pred = model.predict(x_test)

In [11]:
print(model.score(x_test,y_test)*100)

96.66666666666667


In [12]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)
print(cm)
from sklearn.metrics import classification_report
cr = classification_report(y_test,y_pred)
print(cr)

[[11  0  0]
 [ 0 13  0]
 [ 0  1  5]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        11
           1       0.93      1.00      0.96        13
           2       1.00      0.83      0.91         6

    accuracy                           0.97        30
   macro avg       0.98      0.94      0.96        30
weighted avg       0.97      0.97      0.97        30



In [17]:
from sklearn.svm  import SVC

from sklearn import metrics
svc = SVC(probability=True,kernel='linear')

In [23]:
print(model.score(x_test,y_test)*100)

100.0
